#!/usr/bin/env python

# GNOME Specimen, a font preview application for GNOME
# Copyright (C) 2006  Wouter Bolsterlee <uws@xs4all.nl>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA+

PACKAGE="gnome-specimen"
VERSION="0.1"

import gettext
import locale

import pygtk; pygtk.require('2.0');
    
import gtk
import gtk.glade
import gnome

from specimenwindow import SpecimenWindow

# run the program
if __name__ == '__main__':

    prog = gnome.program_init (PACKAGE, VERSION)

    gtk.window_set_default_icon_name ("stock_font")

    w = SpecimenWindow()
    gtk.main ()

